### ISSUE TITLE
Unable to get past 3rd step from the CMake/Visual Studio Building Instructions page.

### ISSUE THREAD

**Issue by Zezimaa** [3dfxdev/EDGE#79]
This is my first time trying to compile anything from source code, and i am trying to follow [the build instructions page](https://github.com/3dfxdev/EDGE/blob/master/build_guide/CMAKE_VSBuild.md) and clicking generate causes an error message to appear:
```
CMake Error at C:/Program Files/CMake/share/cmake-3.20/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
  Could NOT find SDL2 (missing: SDL2_LIBRARY SDL2_INCLUDE_DIR)
Call Stack (most recent call first):
  C:/Program Files/CMake/share/cmake-3.20/Modules/FindPackageHandleStandardArgs.cmake:594 (_FPHSA_FAILURE_MESSAGE)
  cmake/FindSDL2.cmake:171 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  CMakeLists.txt:82 (find_package)
```
I'm quite new to GitHub so I apologise if I'm doing anything wrong, just wanted a bit of help ^^

**Comment by Corbachu** [comment]
Hey! No worries! Glad to see some interest here :) also I apologize those instructions need massive updating... so, assuming we are running Windows and at least MSVC 2015:
Do you by chance run CMake against the project to generate the MSVC solution? 
For this I like to use the CMake-GUI and vcpkg, which allows me to point SDL2 to the dynamic lib, and the rest to static libs via the vcpkg installed libraries. If not using vcpkg (pre-built or otherwise), then you simply need to point to the SDL2 directories/runtimes (and all the other libraries required).

**Comment by Corbachu** [comment]
Feel free to post whatever you have and I’ll help, eventually we will get this compiled! And then I can take some time to update the instructions 😂😂😊

**Comment by Zezimaa** [comment]
I'm afraid I don't know what I'm doing 😅 I just open CMake-gui and set the source location, and click generate as the guide says

**Comment by Zezimaa** [comment]
I've been trying to figure out what to do for the past hour, it's hard because I know essentially nothing about coding, I just wanna use this source port 😅 What would be the easiest way to go about all of this? Also, I apologise if I don't understand something, I'm quite new to this sort of stuff 😓

**Comment by Corbachu** [comment]
You don’t want to use any of the development or compiled builds so far? 

What errors are you getting now? Screenshot of your config would help too

**Comment by Zezimaa** [comment]
Oh- I didn't realise that there were pre-compiled builds '^^ I'll use those, I'm sorry for wasting your time

**Comment by Corbachu** [comment]
Eventually we will get to a place where it’ll be a snap to compile EDGE for any platform; for now I will close the issue.
